name = "Nimbusine"
author = "AIGO Team"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1479a5a721c43c3b8c6be3eb667a50ed0deae035ecb0e658367601a0b641ec40"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.103"
