name = "Nimbusine"
author = "AIGO Team"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6eda26a110e68ae211467ef9d730a37f5027e4db8878d3c4547b12356503ff73"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.103"
