name = "Nimbusine"
author = "AIGO Team"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20021670398e439443d84cebb57384329f8d2a1c4029cd062d0137b8e94a2db0"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.103"
