name = "Nimbusine"
author = "AIGO Team, but really just Verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a3c347a3a99ca421627600a36237efe27468f8b214957a103971d08519ac4eb"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.101"
