name = "Nimbusine"
author = "AIGO Team"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4e720f9f697aee307c4100d96e4ff826704beca47ac1044b57b4bea18b85aa1"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.103"
