name = "Nimbusine"
author = "AIGO Team"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d20d2c93b8d9c26ed3566bab9b491f3d3e76908b5013d6bc72cf8e1156c8a23"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.103"
