name = "Nimbusine"
author = "AIGO Team"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44e8ba75ac04f13361693ad7b93011c268add471fa7a4dfcfeef8c2e2572a3ad"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.103"

[options]
datapack-folder = "config/paxi/datapacks"
