name = "Nimbusine"
author = "AIGO Team"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e1ab7f8470dd6ec4101dd90aa2b661cfbd221b22e2887db015782279d8fdef3"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.103"
