name = "Nimbusine"
author = "AIGO Team, but really just Verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7bb53a4b4dba125c48a44d2c10a0c3601051b78c152571595148ab6ff425fce4"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.101"
