name = "Nimbusine"
author = "AIGO Team"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3fd93967c4fffd0bb9dce148935e0be4dc2ee885a3a03907b3f409a1e8264ac"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.103"
