name = "Nimbusine"
author = "AIGO Team"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "755b2da8449b8d65d2d56e6940b043f8f8068a01ea5868369517641b0525fccc"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.103"

[options]
datapack-folder = "config/paxi/datapacks"
