name = "Nimbusine"
author = "AIGO Team"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "535572350aab773ae0ad258bcd85b335ecf9edb5ac1247a1989549350f2fb5d8"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.103"
