name = "Nimbusine"
author = "AIGO Team"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dccf9d4ae13875d8911e497bb668be2ebb2e7d0274ddf503f7a097816cf7d2df"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.103"
